version: '2'

services:
  web:
    image: procli/php:7.2
    volumes:
      - ./src:/var/www
    ports:
      - "${APP_PORT}:80"
    networks:
      - default
    links:
      - db
      - redis
      - rabbit
      - mailcatcher
    env_file:
      - ./src/.env
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - ./temp/mysql:/var/lib/mysql:delegated
    networks:
      - default
  node:
    image: procli/node:9
    volumes:
      - ./src:/var/www
  redis:
    image: redis:alpine
    volumes:
      - ./temp/redis:/data:cached
    networks:
      - default
    command: redis-server
  rabbit:
    image: rabbitmq:3.6-management
    volumes:
      - ./temp/rabbit:/var/lib/rabbitmq@rabbit:delegated
    networks:
      - default
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
    ports:
      - "15672:15672"
  mailcatcher:
    image: procli/mailcatcher
    networks:
      - default
    ports:
      - "${MAILCATCHER_PORT}:1080"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${MYADMIN_PORT}:80"
    networks:
      - default
    links:
      - db
  echo:
    image: procli/echo
    volumes:
      - ./conf/echo/laravel-echo-server.json:/var/www/laravel-echo-server.json
    ports:
      - "${ECHO_PORT}:6001"
    networks:
      - default
    links:
      - web
      - redis

networks:
  default:
    driver: "bridge"
